# Generated by Django 2.1.15 on 2020-10-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Ingrediant',
        ),
    ]
