# Generated by Django 2.1.15 on 2020-10-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201022_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingrediant',
            new_name='Ingredient',
        ),
    ]
