# Generated by Django 2.1.15 on 2020-10-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_receipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='time_minutest',
            new_name='time_minutes',
        ),
    ]
